services:
  web:
    build: src/
    command: fastapi run src/main.py --port 80
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/foo
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:17.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo